USE finalProj;
CREATE TABLE brand( 
    brandId     INT         NOT NULL,
    brandName   VARCHAR(200) NOT NULL,
    factoryId   INT         NOT NULL,   
    PRIMARY KEY (brandId)
);
insert into brand (brandId, brandName, factoryId) values (1, 'AMOXICILLIN', 5);
insert into brand (brandId, brandName, factoryId) values (2, 'Isopropyl Alcohol Swabs', 5);
insert into brand (brandId, brandName, factoryId) values (3, 'Regonol', 2);
insert into brand (brandId, brandName, factoryId) values (4, 'Human Albumin Grifols', 3);
insert into brand (brandId, brandName, factoryId) values (5, 'Ibuprofen', 2);
insert into brand (brandId, brandName, factoryId) values (6, 'RISPERIDONE', 4);
insert into brand (brandId, brandName, factoryId) values (7, 'Decitabine', 2);
insert into brand (brandId, brandName, factoryId) values (8, 'Methocarbamol', 5);
insert into brand (brandId, brandName, factoryId) values (9, 'OCLIPSE Sunscreen plus Primer Broad-Spectrum SPF 30 UVA/UVB Protection', 1);
insert into brand (brandId, brandName, factoryId) values (10, 'Ibuprofen', 2);
insert into brand (brandId, brandName, factoryId) values (11, 'Quetiapine Fumarate', 5);
insert into brand (brandId, brandName, factoryId) values (12, 'SEROQUEL', 4);
insert into brand (brandId, brandName, factoryId) values (13, 'Sertraline Hydrochloride Tablets', 3);
insert into brand (brandId, brandName, factoryId) values (14, 'ADVAIRDISKUS', 3);
insert into brand (brandId, brandName, factoryId) values (15, 'Major Extra Strength Cold and Hot Pain Relief Therapy', 2);
insert into brand (brandId, brandName, factoryId) values (16, 'Rx Act Antacid', 5);
insert into brand (brandId, brandName, factoryId) values (17, 'Halls', 4);
insert into brand (brandId, brandName, factoryId) values (18, 'Diethylpropion HydrochlorideER', 1);
insert into brand (brandId, brandName, factoryId) values (19, 'Antiseptic Mouth Rinse', 5);
insert into brand (brandId, brandName, factoryId) values (20, 'Sucralfate', 5);
insert into brand (brandId, brandName, factoryId) values (21, 'antibiotic and pain relief', 5);
insert into brand (brandId, brandName, factoryId) values (22, 'ESIKA HYDRACOLOR 2 IN 1 HIGHLY MOISTURIZING AND COLORING SPF 25', 2);
insert into brand (brandId, brandName, factoryId) values (23, 'CARMEX cherry lip balm BROAD SPECTRUM SPF 15 SUNSCREEN', 5);
insert into brand (brandId, brandName, factoryId) values (24, 'Lansoprazole', 3);
insert into brand (brandId, brandName, factoryId) values (25, 'EXTRA STRENGTH WITH NATURAL MENTHOL GLACIER MINT COUGH SUPPRESSANT', 2);
insert into brand (brandId, brandName, factoryId) values (26, 'SORGHUM HALEPENSE POLLEN', 1);
insert into brand (brandId, brandName, factoryId) values (27, 'Gabapentin', 3);
insert into brand (brandId, brandName, factoryId) values (28, 'Captopril', 2);
insert into brand (brandId, brandName, factoryId) values (29, 'First Aid Antiseptic', 3);
insert into brand (brandId, brandName, factoryId) values (30, 'CEFTRIAXONE', 4);
insert into brand (brandId, brandName, factoryId) values (31, 'Bicalutamide', 1);
insert into brand (brandId, brandName, factoryId) values (32, 'All Fresh by Alsco Instant Mist Hand Sanitizer', 2);
insert into brand (brandId, brandName, factoryId) values (33, 'Sure Invisible Solid Powder Scent', 1);
insert into brand (brandId, brandName, factoryId) values (34, 'Losartan Potassium and Hydrochlorothiazide', 3);
insert into brand (brandId, brandName, factoryId) values (35, 'Eagle', 2);
insert into brand (brandId, brandName, factoryId) values (36, 'Ciprofloxacin', 5);
insert into brand (brandId, brandName, factoryId) values (37, 'DESONIDE', 3);
insert into brand (brandId, brandName, factoryId) values (38, 'losartan potassium and hydrochlorothiazide', 4);
insert into brand (brandId, brandName, factoryId) values (39, 'Losartan Potassium and Hydrochlorothiazide', 4);
insert into brand (brandId, brandName, factoryId) values (40, 'ITCHY SKIN ERUPTIONS', 3);
insert into brand (brandId, brandName, factoryId) values (41, 'paroxetine', 1);
insert into brand (brandId, brandName, factoryId) values (42, 'Simvastatin', 3);
insert into brand (brandId, brandName, factoryId) values (43, 'ZIKS ARTHRITIS PAIN RELIEF', 2);
insert into brand (brandId, brandName, factoryId) values (44, 'Instant Hand Sanitizer', 4);
insert into brand (brandId, brandName, factoryId) values (45, 'Pollens - Weeds and Garden Plants, Nettle Urtica dioica', 2);
insert into brand (brandId, brandName, factoryId) values (46, 'LISINOPRIL AND HYDROCHLOROTHIAZIDE', 4);
insert into brand (brandId, brandName, factoryId) values (47, 'OSENI', 3);
insert into brand (brandId, brandName, factoryId) values (48, 'LISINOPRIL AND HYDROCHLOROTHIAZIDE', 3);
insert into brand (brandId, brandName, factoryId) values (49, 'Isordil', 5);
insert into brand (brandId, brandName, factoryId) values (50, 'Food - Plant Source, Pea, Green or English Pisum sativum', 1);
insert into brand (brandId, brandName, factoryId) values (51, 'Levothyroxine Sodium', 3);
insert into brand (brandId, brandName, factoryId) values (52, 'LARIN 1/20', 4);
insert into brand (brandId, brandName, factoryId) values (53, 'FLUCONAZOLE', 3);
insert into brand (brandId, brandName, factoryId) values (54, 'Anti-Bacterial Deep Cleansing Hand', 3);
insert into brand (brandId, brandName, factoryId) values (55, 'medroxyprogesterone acetate', 1);
insert into brand (brandId, brandName, factoryId) values (56, 'Metformin Hydrochloride', 2);
insert into brand (brandId, brandName, factoryId) values (57, 'Mometasone Furoate', 4);
insert into brand (brandId, brandName, factoryId) values (58, 'Extra Strength Gas Relief', 2);
insert into brand (brandId, brandName, factoryId) values (59, 'AQUA COLLAGEN SOLUTION EYE TREATMENT MASK', 3);
insert into brand (brandId, brandName, factoryId) values (60, 'Multi Vitamin Infusion Pediatric', 4);
insert into brand (brandId, brandName, factoryId) values (61, 'Benztropine Mesylate', 4);
insert into brand (brandId, brandName, factoryId) values (62, 'Histenol Forte II', 3);
insert into brand (brandId, brandName, factoryId) values (63, 'Hydroxyzine Hydrochloride', 4);
insert into brand (brandId, brandName, factoryId) values (64, 'simply right cetirizine hydrochloride', 2);
insert into brand (brandId, brandName, factoryId) values (65, 'gas relief', 3);
insert into brand (brandId, brandName, factoryId) values (66, 'ROPINIROLE HYDROCHLORIDE', 5);
insert into brand (brandId, brandName, factoryId) values (67, 'Dental Care Advance Cleaning', 1);
insert into brand (brandId, brandName, factoryId) values (68, 'cefazolin', 3);
insert into brand (brandId, brandName, factoryId) values (69, 'Cefepime', 1);
insert into brand (brandId, brandName, factoryId) values (70, 'Lisinopril', 3);
insert into brand (brandId, brandName, factoryId) values (71, 'SUNSCREEN MOISTURIZER', 4);
insert into brand (brandId, brandName, factoryId) values (72, 'Dexamethasone', 3);
insert into brand (brandId, brandName, factoryId) values (73, 'No7 Protect and Perfect Foundation Sunscreen Broad Spectrum SPF 15 Deeply Beige', 1);
insert into brand (brandId, brandName, factoryId) values (74, 'Analgesic', 2);
insert into brand (brandId, brandName, factoryId) values (75, 'Prednisone', 2);
insert into brand (brandId, brandName, factoryId) values (76, 'pain and fever', 2);
insert into brand (brandId, brandName, factoryId) values (77, 'Triazolam', 2);
insert into brand (brandId, brandName, factoryId) values (78, 'Moxatag', 3);
insert into brand (brandId, brandName, factoryId) values (79, 'White Mulberry', 4);
insert into brand (brandId, brandName, factoryId) values (80, 'Sole', 5);
insert into brand (brandId, brandName, factoryId) values (81, 'Flomax', 1);
insert into brand (brandId, brandName, factoryId) values (82, 'Adderall', 2);
insert into brand (brandId, brandName, factoryId) values (83, 'Eucalyptus Sap Patch', 3);
insert into brand (brandId, brandName, factoryId) values (84, 'Flu Tonic', 2);
insert into brand (brandId, brandName, factoryId) values (85, 'Terrasil S.O.S. Formula', 2);
insert into brand (brandId, brandName, factoryId) values (86, 'Terazosin Hydrochloride', 1);
insert into brand (brandId, brandName, factoryId) values (87, 'KMart', 2);
insert into brand (brandId, brandName, factoryId) values (88, 'Aureobasidium pullulans', 1);
insert into brand (brandId, brandName, factoryId) values (89, 'maximum strength', 3);
insert into brand (brandId, brandName, factoryId) values (90, 'Ofloxacin', 4);
insert into brand (brandId, brandName, factoryId) values (91, 'Warm Sap Patch', 1);
insert into brand (brandId, brandName, factoryId) values (92, 'Triple Complex Digestion Tonic', 4);
insert into brand (brandId, brandName, factoryId) values (93, 'Fentanyl', 2);
insert into brand (brandId, brandName, factoryId) values (94, 'Levetiracetam', 3);
insert into brand (brandId, brandName, factoryId) values (95, 'Nortriptyline Hydrochloride', 3);
insert into brand (brandId, brandName, factoryId) values (96, 'ZIHUA EMBROCATION', 4);
insert into brand (brandId, brandName, factoryId) values (97, 'Brain Power', 3);
insert into brand (brandId, brandName, factoryId) values (98, 'PediaCare Infant Fever Pain Reliever', 2);
insert into brand (brandId, brandName, factoryId) values (99, 'Clear Choice Allergy Relief', 4);
insert into brand (brandId, brandName, factoryId) values (100, 'Dial Gold Bar', 2);
