USE 226operation;
CREATE TABLE brand( 
    brandId     INT             NOT NULL,
    brandName   VARCHAR(200)    NOT NULL,
    factoryId   INT             NOT NULL,   
    PRIMARY KEY (brandId)
);

insert into brand (brandId, brandName, factoryId) values (1, 'Spatheraphy', 5);
insert into brand (brandId, brandName, factoryId) values (2, 'FIREFLY Pediatric', 6);
insert into brand (brandId, brandName, factoryId) values (3, 'LBEL COULEUR LUXE AMPLIFIER XP', 6);
insert into brand (brandId, brandName, factoryId) values (4, 'Hydralazine Hydrochloride', 4);
insert into brand (brandId, brandName, factoryId) values (5, 'pain relief', 4);
insert into brand (brandId, brandName, factoryId) values (6, 'CELEBREX', 5);
insert into brand (brandId, brandName, factoryId) values (7, 'Aspirin', 1);
insert into brand (brandId, brandName, factoryId) values (8, 'Super Restorative Foundation True Lift SPF 15 Tint 08', 3);
insert into brand (brandId, brandName, factoryId) values (9, 'Amlodipine', 3);
insert into brand (brandId, brandName, factoryId) values (10, 'Amazonian Clay BB Tinted Moisturizer Broad Spectrum SPF 20 Sunscreen', 4);
insert into brand (brandId, brandName, factoryId) values (11, 'Sensodyne', 2);
insert into brand (brandId, brandName, factoryId) values (12, 'Extra Strength Pain Relief', 6);
insert into brand (brandId, brandName, factoryId) values (13, 'Lyrica', 6);
insert into brand (brandId, brandName, factoryId) values (14, 'Avocado', 1);
insert into brand (brandId, brandName, factoryId) values (15, 'THERASEPTIN', 2);
insert into brand (brandId, brandName, factoryId) values (16, 'Cefadroxil', 1);
insert into brand (brandId, brandName, factoryId) values (17, 'Glycopyrrolate', 3);
insert into brand (brandId, brandName, factoryId) values (18, 'Fluconazole', 1);
insert into brand (brandId, brandName, factoryId) values (19, 'Ginsamin Energy', 1);
insert into brand (brandId, brandName, factoryId) values (20, 'Halls', 3);
insert into brand (brandId, brandName, factoryId) values (21, 'Duloxetine', 4);
insert into brand (brandId, brandName, factoryId) values (22, 'Pussy Willow', 3);
insert into brand (brandId, brandName, factoryId) values (23, 'Hydrogen Peroxide', 2);
insert into brand (brandId, brandName, factoryId) values (24, 'Headache', 1);
insert into brand (brandId, brandName, factoryId) values (25, 'Gabapentin', 6);
insert into brand (brandId, brandName, factoryId) values (26, 'Aspirin', 5);
insert into brand (brandId, brandName, factoryId) values (27, 'Caldesene Baby', 6);
insert into brand (brandId, brandName, factoryId) values (28, 'Exuviance CoverBlend Concealing Treatment Makeup', 1);
insert into brand (brandId, brandName, factoryId) values (29, 'Digoxin', 4);
insert into brand (brandId, brandName, factoryId) values (30, 'Food - Plant Source, Brazil Nut Bertholletia excelsa', 3);
insert into brand (brandId, brandName, factoryId) values (31, 'misoprostol', 2);
insert into brand (brandId, brandName, factoryId) values (32, 'foundcealer 2-in-1 foundation and concealer Broad Spectrum SPF 15 Sunscreen', 4);
insert into brand (brandId, brandName, factoryId) values (33, 'Topcare Nite Time D', 2);
insert into brand (brandId, brandName, factoryId) values (34, 'Valacyclovir hydrochloride', 6);
insert into brand (brandId, brandName, factoryId) values (35, 'Bug Bouncer', 5);
insert into brand (brandId, brandName, factoryId) values (36, 'ampicillin', 3);
insert into brand (brandId, brandName, factoryId) values (37, 'Atropine Sulfate', 3);
insert into brand (brandId, brandName, factoryId) values (38, 'Lingerie De Peau BB Beauty Booster Invisible Skin-Fusion Multi-Perfecting Makeup With Sunscreen Broad Spectrum SPF 30 MEDIUM', 2);
insert into brand (brandId, brandName, factoryId) values (39, 'Pollens - Trees, Melaleuca (Punk Tree) Melaleuca quinquenervia', 3);
insert into brand (brandId, brandName, factoryId) values (40, 'Australian Gold', 5);
insert into brand (brandId, brandName, factoryId) values (41, 'miconazole 3', 6);
insert into brand (brandId, brandName, factoryId) values (42, 'cephalexin', 5);
insert into brand (brandId, brandName, factoryId) values (43, 'Warfarin Sodium', 2);
insert into brand (brandId, brandName, factoryId) values (44, 'BRAZIL NUT', 1);
insert into brand (brandId, brandName, factoryId) values (45, 'Glimepiride', 5);
insert into brand (brandId, brandName, factoryId) values (46, 'Mometasone Furoate', 1);
insert into brand (brandId, brandName, factoryId) values (47, 'Seasonal Allergy Formula', 4);
insert into brand (brandId, brandName, factoryId) values (48, 'Radiation Protect', 1);
insert into brand (brandId, brandName, factoryId) values (49, 'ZONISAMIDE', 2);
insert into brand (brandId, brandName, factoryId) values (50, 'Anestacon', 4);
insert into brand (brandId, brandName, factoryId) values (51, 'FAMILY WELLNESS TRIPLE ANTIBIOTIC PLUS PAIN RELIEF', 4);
insert into brand (brandId, brandName, factoryId) values (52, 'Peepsing', 1);
insert into brand (brandId, brandName, factoryId) values (53, 'Coralite Antibacterial Moist', 2);
insert into brand (brandId, brandName, factoryId) values (54, 'Ranitidine', 2);
insert into brand (brandId, brandName, factoryId) values (55, 'lice', 5);
insert into brand (brandId, brandName, factoryId) values (56, 'Handtastic Foamy Mango', 1);
insert into brand (brandId, brandName, factoryId) values (57, 'imiquimod', 6);
insert into brand (brandId, brandName, factoryId) values (58, 'PREVPAC', 4);
insert into brand (brandId, brandName, factoryId) values (59, 'Cyclopentolate Hydrochloride', 6);
insert into brand (brandId, brandName, factoryId) values (60, 'Sodium Chloride', 6);
insert into brand (brandId, brandName, factoryId) values (61, 'Phenylephrine Hydrochloride', 5);
insert into brand (brandId, brandName, factoryId) values (62, 'Groundsel', 6);
insert into brand (brandId, brandName, factoryId) values (63, 'Hydrocodone Bitartrate And Acetaminophen', 5);
insert into brand (brandId, brandName, factoryId) values (64, 'TRUFFLE EX WRINKLE', 5);
insert into brand (brandId, brandName, factoryId) values (65, 'EPIVIR', 2);
insert into brand (brandId, brandName, factoryId) values (66, 'Mometasone Furoate', 3);
insert into brand (brandId, brandName, factoryId) values (67, 'Twynsta', 2);
insert into brand (brandId, brandName, factoryId) values (68, 'IMPAVIDO', 5);
insert into brand (brandId, brandName, factoryId) values (69, 'healthy accents cetirizine hydrochloride', 4);
insert into brand (brandId, brandName, factoryId) values (70, 'AlphaNine', 5);
insert into brand (brandId, brandName, factoryId) values (71, 'Clindamycin Hydrochloride', 1);
insert into brand (brandId, brandName, factoryId) values (72, 'IBU', 1);
insert into brand (brandId, brandName, factoryId) values (73, 'Spiced Pumpkin Antibacterial Foaming Hand Wash', 2);
insert into brand (brandId, brandName, factoryId) values (74, 'Womens Laxative', 6);
insert into brand (brandId, brandName, factoryId) values (75, 'Pro1tek Antiseptic Foam Hand Sanitizer', 1);
insert into brand (brandId, brandName, factoryId) values (76, 'Exhaustion - Chronic Fatigue', 6);
insert into brand (brandId, brandName, factoryId) values (77, 'Bupropion Hydrochloride', 1);
insert into brand (brandId, brandName, factoryId) values (78, 'Hydrogen Peroxide', 1);
insert into brand (brandId, brandName, factoryId) values (79, 'DiorSkin Nude 050 Dark Beige', 5);
insert into brand (brandId, brandName, factoryId) values (80, 'SHISEIDO THE SKINCARE TINTED MOISTURE PROTECTION', 1);
insert into brand (brandId, brandName, factoryId) values (81, 'Cranberry', 1);
insert into brand (brandId, brandName, factoryId) values (82, 'OLUX-E', 4);
insert into brand (brandId, brandName, factoryId) values (83, 'Enoxaparin Sodium', 1);
insert into brand (brandId, brandName, factoryId) values (84, 'CARYA OVATA POLLEN', 2);
insert into brand (brandId, brandName, factoryId) values (85, 'Tartar Control Plus', 1);
insert into brand (brandId, brandName, factoryId) values (86, 'Nortriptyline Hydrochloride', 4);
insert into brand (brandId, brandName, factoryId) values (87, 'Asclera', 4);
insert into brand (brandId, brandName, factoryId) values (88, 'Olay Regenerist', 4);
insert into brand (brandId, brandName, factoryId) values (89, 'Doxycycline', 3);
insert into brand (brandId, brandName, factoryId) values (90, 'POLYNESIA LAGOON WATER HYDRO ESSENCE', 3);
insert into brand (brandId, brandName, factoryId) values (91, 'LBEL HYDRATESS', 1);
insert into brand (brandId, brandName, factoryId) values (92, 'Bare Perfecting Makeup', 3);
insert into brand (brandId, brandName, factoryId) values (93, 'CONTROL', 3);
insert into brand (brandId, brandName, factoryId) values (94, 'ESIKA Perfect Match', 4);
insert into brand (brandId, brandName, factoryId) values (95, 'Match Perfection SPF 18', 3);
insert into brand (brandId, brandName, factoryId) values (96, 'Triple Antibiotic', 6);
insert into brand (brandId, brandName, factoryId) values (97, 'Clonidine Hydrochloride', 4);
insert into brand (brandId, brandName, factoryId) values (98, 'Saltbush', 1);
insert into brand (brandId, brandName, factoryId) values (99, 'Cilostazol', 4);
insert into brand (brandId, brandName, factoryId) values (100, 'Lisinopril', 2);
